import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { TopNav } from "./_components/topnav.tsx"
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";

import { ourFileRouter } from "~/app/api/uploadthing/core";


export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by CSHEWES",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
  <ClerkProvider>
  <html lang="en">
  <NextSSRPlugin

    routerConfig={extractRouterConfig(ourFileRouter)}
    />
      <body className={`font-sans flex flex-col gap-4`}>
        <TopNav />
        {children}
      </body>
  </html>
  </ClerkProvider>
  );
}
